"""Tests for the BaseNode contract.

Covers the class-level attribute contract, config merging, injected-callable
nullability, `ui_metadata`, and `report_tokens` routing — everything the
rest of the framework relies on when it instantiates a node.
"""

from __future__ import annotations

import pytest

from choola.core.base_node import BaseNode


class _Dummy(BaseNode):
    """Minimal concrete BaseNode used across tests in this file."""

    node_id = "dummy"
    name = "Dummy"
    category = "processing"
    description = "test"
    fields = [
        {"name": "retries", "type": "number", "default": 3},
        {"name": "label", "type": "string", "default": "hello"},
        {"name": "no_default", "type": "string"},
    ]
    next_nodes = ["next_one"]

    async def execute(self, payload, context):
        return payload


# ---------------------------------------------------------------------------
# Abstract contract
# ---------------------------------------------------------------------------


def test_cannot_instantiate_basenode_directly():
    with pytest.raises(TypeError):
        BaseNode()  # type: ignore[abstract]


def test_subclass_without_execute_is_still_abstract():
    class NoExec(BaseNode):
        pass

    with pytest.raises(TypeError):
        NoExec()  # type: ignore[abstract]


# ---------------------------------------------------------------------------
# Config merging
# ---------------------------------------------------------------------------


def test_config_defaults_populated_from_fields():
    node = _Dummy()
    assert node.config["retries"] == 3
    assert node.config["label"] == "hello"
    # Fields without a default are NOT injected (can't distinguish unset from None).
    assert "no_default" not in node.config


def test_config_overrides_take_precedence_over_defaults():
    node = _Dummy(config={"retries": 10, "extra": "x"})
    assert node.config["retries"] == 10
    assert node.config["label"] == "hello"  # default preserved
    assert node.config["extra"] == "x"  # untyped extras are accepted


def test_node_id_falls_back_to_class_attribute():
    node = _Dummy()
    assert node.node_id == "dummy"


def test_node_id_override_via_constructor():
    node = _Dummy(node_id="custom_id")
    assert node.node_id == "custom_id"


def test_node_id_autogenerated_when_class_attr_blank():
    class Anon(BaseNode):
        async def execute(self, payload, context):
            return payload

    a = Anon()
    b = Anon()
    assert a.node_id and b.node_id
    assert a.node_id != b.node_id
    # 12-char uuid hex slice
    assert len(a.node_id) == 12


# ---------------------------------------------------------------------------
# Injected callables — must raise until the engine populates them
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "attr,args",
    [
        ("get_global", ("k",)),
        ("set_global", ("k", "v")),
        ("get_credential", ("name",)),
        ("db_query", ("SELECT 1",)),
        ("db_execute", ("DELETE FROM x",)),
        ("vector_add", ("coll", ["id"])),
        ("vector_query", ("coll",)),
        ("vector_get", ("coll",)),
        ("vector_delete", ("coll",)),
        ("vector_count", ("coll",)),
    ],
)
async def test_helpers_raise_runtimeerror_when_not_injected(attr, args):
    node = _Dummy()
    with pytest.raises(RuntimeError, match="not injected"):
        await getattr(node, attr)(*args)


async def test_get_global_routes_through_injected_callable():
    node = _Dummy()
    seen: list[str] = []

    async def fake_get(key):
        seen.append(key)
        return "v"

    node._db_get_global = fake_get
    assert await node.get_global("foo") == "v"
    assert seen == ["foo"]


async def test_set_global_routes_through_injected_callable():
    node = _Dummy()
    seen: list[tuple[str, object]] = []

    async def fake_set(key, value):
        seen.append((key, value))

    node._db_set_global = fake_set
    await node.set_global("k", {"a": 1})
    assert seen == [("k", {"a": 1})]


# ---------------------------------------------------------------------------
# Token reporting
# ---------------------------------------------------------------------------


def test_report_tokens_is_noop_when_reporter_missing():
    node = _Dummy()
    # Should not raise even though no reporter was injected — ad-hoc usage.
    node.report_tokens(10, 5, model="m", provider="p")


def test_report_tokens_forwards_to_reporter_with_node_id():
    node = _Dummy(node_id="custom")
    calls: list[tuple] = []
    node._token_reporter = lambda *args: calls.append(args)

    node.report_tokens(100, 50, model="claude-x", provider="anthropic")

    assert calls == [("custom", 100, 50, "claude-x", "anthropic")]


# ---------------------------------------------------------------------------
# UI metadata
# ---------------------------------------------------------------------------


def test_ui_metadata_shape():
    meta = _Dummy.ui_metadata()
    assert meta["name"] == "Dummy"
    assert meta["category"] == "processing"
    assert meta["description"] == "test"
    assert meta["fields"] == _Dummy.fields
    # `type` is a fully-qualified dotted path
    assert meta["type"].endswith("._Dummy")
    assert "test_base_node" in meta["type"]


def test_repr_contains_node_id():
    node = _Dummy(node_id="abc")
    assert "_Dummy" in repr(node)
    assert "abc" in repr(node)
